
### import file
POST http://localhost:8080/api/jokes/import/csv
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="file"; filename="jokes.csv"

< ./jokes.csv
--boundary--

### export file
GET localhost:8080/api/jokes/export/csv


### get all jokes
GET localhost:8080/api/jokes/all

### get random by category
GET localhost:8080/api/jokes/random?category=WEIHNACHTEN

### update
PUT localhost:8080/api/jokes/1
Content-Type: application/json

{
  "witz": "Warum nimmt der Schneemann eine Karotte mit zur Schule? Falls er Nasenarbeit schreiben muss!",
  "kategorie": "WEIHNACHTEN"
}

### like
PATCH localhost:8080/api/jokes/153/like


### create
POST localhost:8080/api/jokes
Content-Type: application/json

{
  "witz": "Warum ging der Kalender zum Arzt? Seine Tage waren gezählt.",
  "kategorie": "ALLGEMEIN"
}

### joke of the day
GET localhost:8080/api/jokes/today

### Top 5 ordered by likes
GET localhost:8080/api/jokes/top


### delete
DELETE localhost:8080/api/jokes/2

