
### import file
POST http://localhost:8080/import/csv
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="file"; filename="jokes.csv"

< ./jokes.csv
--boundary--

### get all jokes
GET localhost:8080/all